function [centroids_L,centroids_nonL,localFeatures_L,localLabels,contextFeatures_L,contextualLabels,graphInterplayFeatures_L,graphInterplayLabels] = getNuclearFeaturesPlay( image,maskL,masknonL )
%GETNUCLEARFEATURES Extracts different features from nuclei.
%mask2 = mask;
% Gray image
grayImg=rgb2gray(image);
orderZernikePol=7;
% Lymphocyte property
% ----------------------------------------------------------------------------------------------%
maskL=maskL(:,:,1);
maskL = logical(maskL);
maskL = bwareaopen(maskL, 30);
regionProperties_L = regionprops(maskL,grayImg,'Centroid','Area',...
    'BoundingBox','Eccentricity','EquivDiameter','Image',...
    'MajorAxisLength','MaxIntensity','MeanIntensity','MinIntensity',...
    'MinorAxisLength','Orientation','PixelValues');
centroids_L = cat(1, regionProperties_L.Centroid);
% ----------------------------------------------------------------------------------------------%
medRed=[]; medGreen=[]; medBlue=[]; entropyRed=[]; medIntensity=[]; entropyIntensity=[]; harFeat=[]; edgeMedIntensity=[]; zernFeat=[];
nucleiNum=size(regionProperties_L,1);
parfor i=1:nucleiNum
    nucleus=regionProperties_L(i);
    bbox = nucleus.BoundingBox;
    bbox = [round(bbox(1)) round(bbox(2)) (bbox(3) - 1) (bbox(4) - 1)];
    roi = image(bbox(2) : bbox(2) + bbox(4), bbox(1) : bbox(1) + bbox(3), :);
    per = bwperim(nucleus.Image);
    gray=rgb2gray(roi);
    R=roi(:,:,1);
    G=roi(:,:,2);
    B=roi(:,:,3);    
    R=R(nucleus.Image == 1);
    G=G(nucleus.Image == 1);
    B=B(nucleus.Image == 1);
    grayPix=gray(nucleus.Image == 1);
    perPix=gray(per==1);
    % Intensity features:
    medRed = [medRed;median(double(R))];
    medGreen = [medGreen;median(double(G))];
    medBlue = [medBlue;median(double(B))];
    medIntensity=[medIntensity;median(double(grayPix))];
    edgeMedIntensity=[edgeMedIntensity;median(double(perPix))];
    % Texture features:
    % Entropies
    entropyRed=[entropyRed; getNucEntropy(R)];
    entropyIntensity=[entropyIntensity;getNucEntropy(grayPix)];
    % Haralick features
    glcm = graycomatrix(gray);    
    harFeat=[harFeat;haralickTextureFeatures(glcm,1:14)'];
    % Zernike moments
    [w,h]=size(nucleus.Image);
    sqRoi=getSquareRoi(grayImg,nucleus.Centroid,w,h);
    zernFeat=[zernFeat;getZernikeMomentsImg(sqRoi,orderZernikePol)];
end
ratioMedRB=medRed./medBlue; ratioMedRG=medRed./medGreen;
ratioAxes=[regionProperties_L.MajorAxisLength]./[regionProperties_L.MinorAxisLength];
localFeatures_L = horzcat([regionProperties_L.Area]',[regionProperties_L.Eccentricity]', ...
    [regionProperties_L.EquivDiameter]',[regionProperties_L.Orientation]', ...
    ratioAxes',entropyIntensity,...
    double([regionProperties_L.MaxIntensity]'),medIntensity,...
    double([regionProperties_L.MinIntensity]'),edgeMedIntensity,entropyRed,...
    ratioMedRB,ratioMedRG,harFeat,zernFeat...
    );
% ----------------------------------------------------------------------------------------------%
masknonL=masknonL(:,:,1);
masknonL = logical(masknonL);
masknonL = bwareaopen(masknonL, 30);
regionProperties_nonL = regionprops(masknonL,grayImg,'Centroid','Area',...
    'BoundingBox','Eccentricity','EquivDiameter','Image',...
    'MajorAxisLength','MaxIntensity','MeanIntensity','MinIntensity',...
    'MinorAxisLength','Orientation','PixelValues');
centroids_nonL = cat(1, regionProperties_nonL.Centroid);
% % ----------------------------------------------------------------------------------------------%
% medRed=[]; medGreen=[]; medBlue=[]; entropyRed=[]; medIntensity=[]; entropyIntensity=[]; harFeat=[]; edgeMedIntensity=[]; zernFeat=[];
% nucleiNum=size(regionProperties_nonL,1);
% for i=1:nucleiNum
%     nucleus=regionProperties_nonL(i);
%     bbox = nucleus.BoundingBox;
%     bbox = [round(bbox(1)) round(bbox(2)) (bbox(3) - 1) (bbox(4) - 1)];
%     roi = image(bbox(2) : bbox(2) + bbox(4), bbox(1) : bbox(1) + bbox(3), :);
%     per = bwperim(nucleus.Image);
%     gray=rgb2gray(roi);
%     R=roi(:,:,1);
%     G=roi(:,:,2);
%     B=roi(:,:,3);    
%     R=R(nucleus.Image == 1);
%     G=G(nucleus.Image == 1);
%     B=B(nucleus.Image == 1);
%     grayPix=gray(nucleus.Image == 1);
%     perPix=gray(per==1);
%     % Intensity features:
%     medRed = [medRed;median(double(R))];
%     medGreen = [medGreen;median(double(G))];
%     medBlue = [medBlue;median(double(B))];
%     medIntensity=[medIntensity;median(double(grayPix))];
%     edgeMedIntensity=[edgeMedIntensity;median(double(perPix))];
%     % Texture features:
%     % Entropies
%     entropyRed=[entropyRed; getNucEntropy(R)];
%     entropyIntensity=[entropyIntensity;getNucEntropy(grayPix)];
%     % Haralick features
%     glcm = graycomatrix(gray);    
%     harFeat=[harFeat;haralickTextureFeatures(glcm,1:14)'];
%     % Zernike moments
%     [w,h]=size(nucleus.Image);
%     sqRoi=getSquareRoi(grayImg,nucleus.Centroid,w,h);
%     zernFeat=[zernFeat;getZernikeMomentsImg(sqRoi,orderZernikePol)];
% end
% ratioMedRB=medRed./medBlue; ratioMedRG=medRed./medGreen;
% ratioAxes=[regionProperties_nonL.MajorAxisLength]./[regionProperties_nonL.MinorAxisLength];
% localFeatures_nonL = horzcat([regionProperties_nonL.Area]',[regionProperties_nonL.Eccentricity]', ...
%     [regionProperties_nonL.EquivDiameter]',[regionProperties_nonL.Orientation]', ...
%     ratioAxes',entropyIntensity,...
%     double([regionProperties_nonL.MaxIntensity]'),medIntensity,...
%     double([regionProperties_nonL.MinIntensity]'),edgeMedIntensity,entropyRed,...
%     ratioMedRB,ratioMedRG,harFeat,zernFeat...
% );
% ----------------------------------------------------------------------------------------------%

% Check the mean of the diameter of all nuclei of a image
%des = horzcat( [regionProperties.EquivDiameter]' );
%mean(des)

% Contextual Features
% Basic features regarding local information e.g. (area, ecc, intensity, quantity, distances)
% 
[~, ~, ~, ~, filtquantvarmat, filtareasvarmat, filtareasmeanmat, filtareasmedianmat,...
filtareasstdmat, filteccentricityvarmat, filteccentricitymeanmat, filteccentricitymedianmat, filteccentricitystdmat,...
filtdiametervarmat, filtdiametermeanmat, filtdiametermedianmat, filtdiameterstdmat, filtmeanIntensityvarmat,...
filtmeanIntensitymeanmat, filtmeanIntensitymedianmat, filtmeanIntensitystdmat, filtentropyRedvarmat,...
filtentropyRedmeanmat, filtentropyRedmedianmat, filtentropyRedstdmat, filtratioRedBbluevarmat, filtratioRedBbluemeanmat,...
filtratioRedBbluemedianmat, filtratioRedBbluestdmat, filtratioRedGreenvarmat,  filtratioRedGreenmeanmat,...
filtratioRedGreenmedianmat,  filtratioRedGreenstdmat] = getCentroidsByTresh(...
centroids_L, [regionProperties_L.Area]',[regionProperties_L.Eccentricity]',...
[regionProperties_L.EquivDiameter]',medIntensity,entropyRed,ratioMedRB,ratioMedRG...
);

%%%%%% Lines for checking the centroids

%imgmark = insertMarker(image, [filtcentroids{3,600}(:,1), filtcentroids{3,600}(:,2)],'*','color','blue','size',10);
%imgmark2 = insertMarker(mask2, [filtcentroids{3,600}(:,1), filtcentroids{3,600}(:,2)],'*','color','blue','size',10);
%imwrite(imgmark, '/mnt/data/home/crb138/Datasets/Breast_Cancer_Challenge/Feats/test.png')
%imwrite(imgmark2, '/mnt/data/home/crb138/Datasets/Breast_Cancer_Challenge/Feats/test2.png')
%pause
%%%%%%
contextFeatures_L = horzcat(filtquantvarmat, filtareasvarmat, filtareasmeanmat, filtareasmedianmat,...
filtareasstdmat, filteccentricityvarmat, filteccentricitymeanmat, filteccentricitymedianmat, filteccentricitystdmat,...
filtdiametervarmat, filtdiametermeanmat, filtdiametermedianmat, filtdiameterstdmat, filtmeanIntensityvarmat,...
filtmeanIntensitymeanmat, filtmeanIntensitymedianmat, filtmeanIntensitystdmat, filtentropyRedvarmat,...
filtentropyRedmeanmat, filtentropyRedmedianmat, filtentropyRedstdmat, filtratioRedBbluevarmat, filtratioRedBbluemeanmat,...
filtratioRedBbluemedianmat, filtratioRedBbluestdmat, filtratioRedGreenvarmat,  filtratioRedGreenmeanmat,...
filtratioRedGreenmedianmat,  filtratioRedGreenstdmat...
);
%contextualfeatures = horzcat(filtareasmat, filteccentricitymat, filtdiametermat, filtmeanIntensitymat, filtentropyRedmat,...
%     sumInvDistNuc, filtratioRedBbluemat, filtratioRedGreenmat...
%     );
localLabels={'Area','Eccentricity','EquivDiameter','Orientation','ratioAxes','entropyIntensity',...
'MaxIntensity','medIntensity','MinIntensity','edgeMedIntensity','entropyRed','ratioMedRB ','ratioMedRG',...
'harFeat_energyAngularSecondMoment','harFeat_Contrast','harFeat_correlation','harFeat_Variance',...
'harFeat_InverseDifferenceMoment','harFeat_SumAverage','harFeat_SumVariance','harFeat_SumEntropy',...
'harFeat_Entropy','harFeat_DifferenceVariance','harFeat_DifferenceEntropy','harFeat_InformationMeasuresCorrelationI',...
'harFeat_InformationMeasuresCorrelationII','harFeat_MaximalCorrelationCoefficient','zernFeat1','zernFeat2',...
'zernFeat3','zernFeat4','zernFeat5','zernFeat6','zernFeat7','zernFeat8','zernFeat9','zernFeat10','zernFeat11',...
'zernFeat12','zernFeat13','zernFeat14','zernFeat15','zernFeat16','zernFeat17','zernFeat18','zernFeat19',...
'zernFeat20','zernFeat21','zernFeat22','zernFeat23','zernFeat24','zernFeat25','zernFeat26','zernFeat27',...
'zernFeat28','zernFeat29','zernFeat30','zernFeat31','zernFeat32','zernFeat33','zernFeat34','zernFeat35',...
'zernFeat36','zernFeat37','zernFeat38','zernFeat39','zernFeat40','zernFeat41','zernFeat42','zernFeat43',...
'zernFeat44','zernFeat45','zernFeat46','zernFeat47','zernFeat48','zernFeat49','zernFeat50','zernFeat51',...
'zernFeat52','zernFeat53','zernFeat54','zernFeat55','zernFeat56','zernFeat57','zernFeat58','zernFeat59',...
'zernFeat60','zernFeat61','zernFeat62','zernFeat63','zernFeat64','zernFeat65','zernFeat66','zernFeat67',...
'zernFeat68','zernFeat69','zernFeat70','zernFeat71','zernFeat72'};
contextualLabels={'filtquantvarmatK1','filtquantvarmatK2','filtquantvarmatK3','filtareasvarmatK1',...
'filtareasvarmatK2','filtareasvarmatK3','filtareasmeanmatK1','filtareasmeanmatK2','filtareasmeanmatK3',...
'filtareasmedianmatK1','filtareasmedianmatK2','filtareasmedianmatK3','filtareasstdmatK1','filtareasstdmatK2',...
'filtareasstdmatK3','filteccentricityvarmatK1','filteccentricityvarmatK2','filteccentricityvarmatK3',...
'filteccentricitymeanmatK1','filteccentricitymeanmatK2','filteccentricitymeanmatK3','filteccentricitymedianmatK1',...
'filteccentricitymedianmatK2','filteccentricitymedianmatK3','filteccentricitystdmatK1','filteccentricitystdmatK2',...
'filteccentricitystdmatK3','filtdiametervarmatK1','filtdiametervarmatK2','filtdiametervarmatK3',...
'filtdiametermeanmatK1','filtdiametermeanmatK2','filtdiametermeanmatK3','filtdiametermedianmatK1',...
'filtdiametermedianmatK2','filtdiametermedianmatK3','filtdiameterstdmatK1','filtdiameterstdmatK2',...
'filtdiameterstdmatK3','filtmeanIntensityvarmatK1','filtmeanIntensityvarmatK2','filtmeanIntensityvarmatK3',...
'filtmeanIntensitymeanmatK1','filtmeanIntensitymeanmatK2','filtmeanIntensitymeanmatK3',...
'filtmeanIntensitymedianmatK1','filtmeanIntensitymedianmatK2','filtmeanIntensitymedianmatK3',...
'filtmeanIntensitystdmatK1','filtmeanIntensitystdmatK2','filtmeanIntensitystdmatK3','filtentropyRedvarmatK1',...
'filtentropyRedvarmatK2','filtentropyRedvarmatK3','filtentropyRedmeanmatK1','filtentropyRedmeanmatK2',...
'filtentropyRedmeanmatK3','filtentropyRedmedianmatK1','filtentropyRedmedianmatK2','filtentropyRedmedianmatK3',...
'filtentropyRedstdmatK1','filtentropyRedstdmatK2','filtentropyRedstdmatK3','filtratioRedBbluevarmatK1',...
'filtratioRedBbluevarmatK2','filtratioRedBbluevarmatK3','filtratioRedBbluemeanmatK1','filtratioRedBbluemeanmatK2',...
'filtratioRedBbluemeanmatK3','filtratioRedBbluemedianmatK1','filtratioRedBbluemedianmatK2',...
'filtratioRedBbluemedianmatK3','filtratioRedBbluestdmatK1','filtratioRedBbluestdmatK2','filtratioRedBbluestdmatK3',...
'filtratioRedGreenvarmatK1','filtratioRedGreenvarmatK2','filtratioRedGreenvarmatK3','filtratioRedGreenmeanmatK1',...
'filtratioRedGreenmeanmatK2','filtratioRedGreenmeanmatK3','filtratioRedGreenmedianmatK1',...
'filtratioRedGreenmedianmatK2','filtratioRedGreenmedianmatK3','filtratioRedGreenstdmat','filtratioRedGreenstdma2',...
'filtratioRedGreenstdma3'};
graphInterplayLabels = {'sumInvDistLympK1','sumInvDistLympK2','sumInvDistLympK3','RatioAreaLympNonLympK1',...
'RatioAreaLympNonLympK2','RatioAreaLympNonLympK3','ratioAreaLympSampleK1','ratioAreaLympSampleK2',...
'ratioAreaLympSampleK3','ratioNumLympNonLympK1','ratioNumLympNonLympK2',...
'ratioNumLympNonLympK3','intensityDifferenceMedianK1','intensityDifferenceMedianK2',...
'intensityDifferenceMedianK3','convexHullAreaRatioK1','convexHullAreaRatioK2',...
'convexHullAreaRatioK3','convexHullIntersectedAreaK1','convexHullIntersectedAreaK2',...
'convexHullIntersectedAreaK3','mediamDistLympNonLympNeigK1','mediamDistLympNonLympNeigK2',...
'mediamDistLympNonLympNeigK3','ratioMediamDistLympNonLympNeigK1',...
'ratioMediamDistLympNonLympNeigK2','ratioMediamDistLympNonLympNeigK3',...
'numLymInNonLympAreaK1','numLymInNonLympAreaK2','numLymInNonLympAreaK3',...
'sumDistLymptoNonLympK1','sumDistLymptoNonLympK2','sumDistLymptoNonLympK3',...
'sampleAreaK1','sampleentropyIntensityK1','sampleMaxIntensityK1',...
'samplemedIntensityK1','sampleMinIntensityK1','sampleedgeMedIntensityK1',...
'sampleentropyRedK1','sampleratioMedRBK1','sampleratioMedRGK1',...
'sampleharFeat_energyAngularSecondMomentK1','sampleharFeat_ContrastK1',...
'sampleharFeat_correlationK1','sampleharFeat_VarianceK1','sampleharFeat_InverseDifferenceMomentK1',...
'sampleharFeat_SumAverageK1','sampleharFeat_SumVarianceK1','sampleharFeat_SumEntropyK1',...
'sampleharFeat_EntropyK1','sampleharFeat_DifferenceVarianceK1','sampleharFeat_DifferenceEntropyK1',...
'sampleharFeat_InformationMeasuresCorrelationIK1','sampleharFeat_InformationMeasuresCorrelationIIK1',...
'sampleharFeat_MaximalCorrelationCoefficientK1','sampleAreaK2','sampleentropyIntensityK2',...
'sampleMaxIntensityK2','samplemedIntensityK2','sampleMinIntensityK2','sampleedgeMedIntensityK2',...
'sampleentropyRedK2','sampleratioMedRBK2','sampleratioMedRGK2',...
'sampleharFeat_energyAngularSecondMomentK2','sampleharFeat_ContrastK2',...
'sampleharFeat_correlationK2','sampleharFeat_VarianceK2','sampleharFeat_InverseDifferenceMomentK2',...
'sampleharFeat_SumAverageK2','sampleharFeat_SumVarianceK2','sampleharFeat_SumEntropyK2',...
'sampleharFeat_EntropyK2','sampleharFeat_DifferenceVarianceK2',...
'sampleharFeat_DifferenceEntropyK2','sampleharFeat_InformationMeasuresCorrelationIK2',...
'sampleharFeat_InformationMeasuresCorrelationIIK2',...
'sampleharFeat_MaximalCorrelationCoefficientK2','sampleAreaK3','sampleentropyIntensityK3',...
'sampleMaxIntensityK3','samplemedIntensityK3','sampleMinIntensityK3','sampleedgeMedIntensityK3',...
'sampleentropyRedK3','sampleratioMedRBK3','sampleratioMedRGK3',...
'sampleharFeat_energyAngularSecondMomentK3','sampleharFeat_ContrastK3',...
'sampleharFeat_correlationK3','sampleharFeat_VarianceK3',...
'sampleharFeat_InverseDifferenceMomentK3','sampleharFeat_SumAverageK3',...
'sampleharFeat_SumVarianceK3','sampleharFeat_SumEntropyK3','sampleharFeat_EntropyK3',...
'sampleharFeat_DifferenceVarianceK3','sampleharFeat_DifferenceEntropyK3',...
'sampleharFeat_InformationMeasuresCorrelationIK3',...
'sampleharFeat_InformationMeasuresCorrelationIIK3','sampleharFeat_MaximalCorrelationCoefficientK3'};
% Put together the Lymp % nonLymp features
nucleiCentroids = [centroids_L; centroids_nonL];
nucleiArea = [[regionProperties_L.Area]';[regionProperties_nonL.Area]'];
MeanIntensity  = [[regionProperties_L.MeanIntensity]';[regionProperties_nonL.MeanIntensity]'];
% Put labels on the nuclei. 1 = Lymp,   2  = nonlymp.
nucpredL = ones(length(centroids_L),1);
nucprednonL = 2*ones(length(centroids_nonL),1);
nucleiPrediction = [nucpredL;nucprednonL];
% Extract Interplay features
[graphInterplayFeatures] = getGraphNucleiFeatures(nucleiCentroids,nucleiArea,MeanIntensity,nucleiPrediction,image);
% Limit the graph features into only for lymphocytes
graphInterplayFeatures_L = graphInterplayFeatures(1:length(nucpredL),:);
% Limit the graph features into cancerous cells
%graphInterplayFeatures_nonL = graphInterplayFeatures(1:length(nucprednonL),:);
end

