#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# TO CHANGE FOR OTHER ENVIRONMENT MORE EASY, SET run_matlab or run_python as 'Set as File to Run' to run specific codes

# TO RUN SET ENVIRONMENT TO: MATLAB (2021b-ubuntu20.04)

# Set of PhenoTIL features that are extracted from a single lymphocyte cell on the H&E-stained patch. It outputs 288 feature vectors per cell.
matlab -nodisplay -r "addpath(genpath('.')); getAllFeatures_V2 '/data/' '/results/'"

# TO RUN SET ENVIRONMENT TO: TensorFlow (Python 2.7) (1.4.0) and add scikit-learn: 0.18.1

# The set of PhenoTIL feature vectors are then used to group or clusterize the cells into either 8 different groups, using unsupervised process, Dirichlet Process Gaussian Mixture Model (DPGMM)
# jupyter nbconvert --to python clustering_lcs_V2.ipynb
python clustering_lcs_V2.py

# TO RUN SET ENVIRONMENT TO: R (4.1.0, RStudio 1.4.1106) - IF CODE DOES NOT RUN, RUN IN A LOCAL PC
# R (CRAN) survival
# R (Github) kassambara/survminer


# Plot different figures used in the manuscript
Rscript template_plot_phenoTIL.R