#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# TO CHANGE FOR OTHER ENVIRONMENT MORE EASY, SET run_matlab or run_python as 'Set as File to Run' to run specific codes

# TO RUN SET ENVIRONMENT TO: R (4.1.0, RStudio 1.4.1106)
# Plot different figures used in the manuscript
Rscript template_plot_phenoTIL.R