#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# TO RUN SET ENVIRONMENT TO: TensorFlow (Python 2.7) (1.4.0) and add scikit-learn: 0.18.1

# The set of PhenoTIL feature vectors are then used to group or clusterize the cells into either 8 different groups, using unsupervised process, Dirichlet Process Gaussian Mixture Model (DPGMM)
# jupyter nbconvert --to python clustering_lcs_V2.ipynb
python clustering_lcs_V2.py