#!/bin/bash
#SBATCH --job-name=LympIdent
#SBATCH -o outcome/LIdent_%A_%a.out
#SBATCH -e outcome/LIdent_%A_%a.err
#SBATCH --array=1-2
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=64G
#SBATCH --time=100:00:00

module load matlab/R2016b
matlab -nodisplay -r "fullLympIdent_TMA("$SLURM_ARRAY_TASK_ID");exit"
